mysite/blog/urls.py
# -*-coding:utf-8-*-
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from utils.upload import upload_file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls')),

    path('uploads/', upload_file, name='upload')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
# -*-coding:utf-8-*-
from django.urls import path
from . import views

app_name = 'users'  # 定义一个命名空间，用来区分不同应用之间的链接地址

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('active/<active_code>', views.active_user, name='active_user'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forget_pwd_url/<active_code>', views.forget_pwd_url, name='forget_pwd_url'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('logout/', views.logout_view, name='logout'),
    path('editor_users/', views.editor_users, name='editor_users'),
]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    USER_GENDER_TYPE = (
        ('male', '男'),
        ('female', '女'),
    )

    owner = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='用户')
    nike_name = models.CharField('昵称', max_length=23, blank=True, default='')
    desc = models.TextField('个人简介', max_length=200, blank=True, default='')
    signature = models.CharField('个性签名', max_length=100, blank=True, default='')
    birthday = models.DateField('生日', null=True, blank=True)
    gender = models.CharField('性别', max_length=6, choices=USER_GENDER_TYPE, default='male')
    address = models.CharField('地址', max_length=100, blank=True, default='')
    image = models.ImageField(upload_to='images/%Y/%m', default='images/default.jpg', max_length=100, verbose_name='用户头像')

    class Meta:
        verbose_name = '用户数据'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.owner.username


class EmailVerifyRecord(models.Model):
    """ 邮箱验证码校验记录 """
    SEND_TYPE_CHOICES = (
        ('register', '注册'),
        ('forget', '找回密码'),
    )
    code = models.CharField('验证码', max_length=20)
    email = models.EmailField('邮箱', max_length=35)
    send_type = models.CharField(choices=SEND_TYPE_CHOICES, default='register', max_length=20)

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.code

mysite/users/forms.py
# -*-coding:utf-8-*-
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=32, widget=forms.TextInput(attrs={
        'class': 'input', 'placeholder': '用户名/邮箱'
    }))
    password = forms.CharField(label='密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '密码'
    }))

    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username == password:
            raise forms.ValidationError('用户名与密码不能相同！')
        return password


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label='邮箱', min_length=6, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': '用户名/邮箱'
    }))
    password = forms.CharField(label='密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '密码'
    }))
    password_retry = forms.CharField(label='再次输入密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '密码'
    }))

    class Meta:
        model = User
        fields = ['email', 'password']

    def clean_email(self):
        """ 验证用户是否存在 """
        email = self.cleaned_data.get('email')
        exists = User.objects.filter(email=email).exists()
        if exists:
            raise forms.ValidationError('用户名已经存在')
        return email

    def clean_password_retry(self):
        """ 两次输入密码验证 """
        password = self.cleaned_data.get('password')
        password_retry = self.cleaned_data.get('password_retry')
        if password != password_retry:
            raise forms.ValidationError('两次输入密码不一致')
        return password_retry


class ForgetPwdForm(forms.Form):
    """ 填写email表单页面 """
    email = forms.EmailField(label='请输入注册邮箱地址', min_length=4, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': '用户名/邮箱'
    }))


class ModifyPwdForm(forms.Form):
    """修改密码表单"""
    password = forms.CharField(label="输入新密码", min_length=6,
        widget=forms.PasswordInput(attrs={'class': 'input', 'placeholder': '输入密码'}))


class UserForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'input', 'disabled': 'disabled'
    }))

    class Meta:
        model = User
        fields = ('email',)


class UserProfileForm(forms.ModelForm):
    """Form definition for UserInfo."""

    class Meta:
        """Meta definition for UserInfoform."""

        model = UserProfile
        fields = ('nike_name', 'desc', 'signature', 'birthday', 'gender', 'address', 'image')

mysite/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.contrib.auth.hashers import make_password
from .models import EmailVerifyRecord, UserProfile
from .forms import LoginForm, RegisterForm, ForgetPwdForm, ModifyPwdForm, UserForm, UserProfileForm
from utils.email_send import send_register_email
from django.contrib.auth.decorators import login_required


class MyBackend(ModelBackend):
    """ 邮箱登录注册 """
    def authenticate(self, request, username=None, password=None):
        try:
            user = User.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


def active_user(request, active_code):
    """ 修改用户状态，比对链接验证码 """
    all_records = EmailVerifyRecord.objects.filter(code=active_code)
    if all_records:
        for record in all_records:
            email = record.email
            user = User.objects.get(email=email)
            user.is_staff = True
            user.save
    else:
        return HttpResponse('链接有误')


def login_view(request):
    if request.method == "GET":
        form = LoginForm()
    form = LoginForm(request.POST)
    if form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('users:user_profile')
        else:
            return HttpResponse("登录失败")
    context = {
        'form': form
    }
    return render(request, 'users/login.html', context)


def register(request):
    """ 注册视图 """
    if request.method != "POST":
        form = RegisterForm()
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data.get('password'))
            new_user.username = form.cleaned_data.get('email')
            new_user.save()

            # 发送邮件
            send_register_email(form.cleaned_data.get('email'), 'register')
            return HttpResponse('注册成功')
    context = {'form': form}
    return render(request, 'users/register.html', context)


def forget_pwd(request):
    """ 填写邮箱地址发送邮件表单页面 """
    if request.method == 'GET':
        form = ForgetPwdForm()
    elif request.method == 'POST':
        form = ForgetPwdForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            exists = User.objects.filter(email=email).exists()
            if exists:
                send_register_email(email, 'forget')
                return HttpResponse('邮件已经发送请查收！')
            else:
                return HttpResponse('邮箱还未注册，请前往注册！')

    return render(request, 'users/forget_pwd.html', {'form': form})


def forget_pwd_url(request, active_code):
    """ 发送邮箱链接视图，并修改密码 """
    if request.method != 'POST':
        form = ModifyPwdForm()
    else:
        form = ModifyPwdForm(request.POST)
        if form.is_valid():
            record = EmailVerifyRecord.objects.get(code=active_code)
            email = record.email
            user = User.objects.get(email=email)
            user.username = email
            user.password = make_password(form.cleaned_data.get('password'))
            user.save()
            return HttpResponse('修改成功')
        else:
            return HttpResponse('修改失败')

    return render(request, 'users/reset_pwd.html', {'form': form})


@login_required(login_url='users:login')
def user_profile(request):
    """ 用户中心 """
    user = User.objects.get(username=request.user)
    return render(request, 'users/user_profile.html', {'user': user})


def logout_view(request):
    logout(request)
    return redirect('users:login')


@login_required(login_url='users:login')   # 登录之后允许访问
def editor_users(request):
    """ 编辑用户信息 """
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        try:
            userprofile = user.userprofile
            form = UserForm(request.POST, instance=user)
            user_profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)  # 向表单填充默认数据
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                user_profile_form.save()
                return redirect('users:user_profile')
        except UserProfile.DoesNotExist:  # 这里发生错误说明userprofile无数据
            form = UserForm(request.POST, instance=user)  # 填充默认数据 当前用户
            user_profile_form = UserProfileForm(request.POST, request.FILES)  # 空表单，直接获取空表单的数据保存
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                # commit=False 先不保存，先把数据放在内存中，然后再重新给指定的字段赋值添加进去，提交保存新的数据
                new_user_profile = user_profile_form.save(commit=False)
                new_user_profile.owner = request.user
                new_user_profile.save()

                return redirect('users:user_profile')
    else:
        try:
            userprofile = user.userprofile
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm(instance=userprofile)
        except UserProfile.DoesNotExist:
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm()  # 显示空表单
    return render(request, 'users/editor_users.html', locals())

mysite/users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'users/bulma.css' %}">
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

mysite/users/templates/users/editor_users.html
{% extends 'users/user_profile.html' %}

<!-- 如何覆盖掉继承模板文件中原有的东西 -->


{% block title %}
<li class="is-active"><a>编辑用户</a></li>
{% endblock  %}

{% block content %}

<!-- 官方文档： https://docs.djangoproject.com/zh-hans/3.2/topics/forms/ -->
<form action="{% url 'users:editor_users' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field is-horizontal">
        <div class="field-label is-normal">
          <label for="{{ form.email.id_for_label }}" class="label">{{ form.email.label }}</label>
        </div>
        <div class="field-body">
          <div class="field">
            <div class="control">
                {{ form.email }}
            </div>
          </div>
        </div>
    </div>
      {% for field in user_profile_form %}
      <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
          </div>
          <div class="field-body">
            <div class="field">
              <div class="control">
                 {{ field }}
              </div>
            </div>
          </div>
      </div>
      {% endfor %}
      <input class=" button is-primary is-pulled-right" type="submit" value="保存修改">
      <div class=" is-clearfix"></div>

  </form>
{% endblock %}

mysite/users/templates/users/forget_pwd.html
{% extends 'users/base.html' %}


{% block head %}
    <title>输入邮箱地址发送邮件找回密码</title>
{% endblock head %}

{% block content %}
    <div class="box">
        <h1 class="is-uppercase has-text-centered has-text-weight-bold">找回密码
            <br><span class="tag">请输入注册邮箱</span>
        </h1>
        <hr class=" dropdown-divider">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.errors }}
            
            <input type="submit" style="margin-top: 1em;" class="button is-link is-fullwidth" value="提 交">
        </form>
    </div>

{% endblock content %}

mysite/users/templates/users/login.html
{% extends 'users/base.html' %}
{% block head %}
<title>登录页面</title>
{% endblock %}


{% block content %}
    <div class="box">
        <h1 class="is-uppercase has-text-centered has-text-weight-bold">登录页面
            <br><span class="tag">登录</span>
        </h1>
        <hr class="dropdown-divider">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <a class=" is-pulled-right is-size-7" href="{% url 'users:forget_pwd' %}">忘记密码?</a>
            <input type="submit" class="button is-link is-fullwidth" value="提交">

        </form>
    </div>
{% endblock %}

mysite/users/templates/users/register.html
{% extends 'users/base.html' %}
{% block head %}
<title>注册页面</title>
{% endblock %}

{% block content %}
    <div class="box">
        <h1 class="is-uppercase has-text-centered has-text-weight-bold">注册页面
            <br><span class="tag">注册</span>
        </h1>
        <hr class="dropdown-divider">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="button is-link is-fullwidth" value="注册">
        </form>
    </div>
{% endblock %}

mysite/users/templates/users/reset_pwd.html
{% extends 'users/base.html' %}


{% block head %}
    <title>修改密码页面</title>
{% endblock head %}
    

{% block content %}
    <div class="box">
        <h1 class="is-uppercase has-text-centered has-text-weight-bold">输入密码
            <br><span class="tag">修改密码</span>
        </h1>
        <hr class=" dropdown-divider">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.errors }}
           
            <input type="submit" style="margin-top: 1em;" class="button is-link is-fullwidth" value="提 交">
        </form>
    </div>

{% endblock content %}

mysite/users/templates/users/user_profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>个人中心</title>
    <link rel="stylesheet" href=" {% static 'users/bulma.css' %} ">
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <script src=" {% static 'users/js/all.min.js' %}"></script>
</head>
<body>
    <!-- 头部导航 -->
    <nav class="navbar">
        <div class="container">
            <div class="navbar-brand">
                <a href="\" class="navbar-item">
                    <img src="{% static 'users/images/default.jpg' %}" width="112" height="28" alt="logo">
                </a>
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class=" dropdown is-hoverable">
                            <div class="dropdown-trigger">
                                <button class=" button is-white">
                                    <figure class="image is-24x24">

                                        {% if user.userprofile.image %}
                                            <img class=" is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}" alt="" srcset="">
                                        {% else %}
                                            <img class=" is-rounded" src="{% static 'users/images/default.jpg' %}" alt="" srcset="">
                                        {% endif %}
                                    </figure>&nbsp;&nbsp;

                                        {% if user.userprofile.nike_name %}
                                        <span class="has-text-grey-dark">{{ user.userprofile.nike_name }}</span>
                                        {% else %}
                                        <span class="has-text-grey-dark">{{ user.username }}</span>
                                        {% endif %}
                                        <span class="icon is-small">
                                            <i class="fas fa-angle-down" aria-hidden="true"></i>
                                        </span>
                                </button>
                            </div>

                            <div class="dropdown-menu" id="dropdown-menu2" role="menu" >
                                <div class="dropdown-content is-shadowless">
                                    <div class="dropdown-item">
                                        <a class=" has-text-grey-dark" href="">
                                            <span class="icon is-small">
                                                <i class="fas fa-user-cog" aria-hidden="true"></i>
                                            </span>&nbsp;&nbsp;
                                           <a href="{% url 'users:editor_users' %}">账号设置</a>
                                        </a>
                                    </div>
                                    <hr class="dropdown-divider">
                                    <div class="dropdown-item">
                                        <a class=" has-text-grey-dark" href="{% url 'users:logout' %}">
                                            <span class="icon is-small">
                                                <i class="fas fa-power-off" aria-hidden="true"></i>
                                            </span>&nbsp;&nbsp;
                                            退出登录
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </nav>

    <section class="section">
        <div class="container">

            <div class="columns">
                <div class="column is-2">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">个人中心</p>
                            <a href="" class="card-header-icon" aria-label="more options">
                                <span class="icon">
                                    <i class="fas fa-angle-down" aria-hidden="true"></i>
                                </span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                                <li><a href="{% url 'users:user_profile' %}">个人信息</a></li>
                                <!-- <li><a href="">修改密码</a></li> -->

                            </ul>
                        </div>

                    </div>
                    <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">内容管理</p>
                                <a href="#" class="card-header-icon" aria-label="more options">
                                    <span class="icon">
                                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </header>
                            <div class="card-content menu">
                                <ul class="content menu-list">
                                    <li><a href="">添加文章</a></li>
                                    <li><a href="">已发布</a></li>
                                    <li><a href="">草稿箱</a></li>
                                    <li><a href="">评论管理</a></li>
                                    <li><a href="">数据分析</a></li>
                                </ul>
                            </div>

                    </div>
                </div>
                <div class="column is-10">
                    <div class="box is-radiusless is-shadowless">

                        <div class="tabs">
                            <ul>

                              {% block title %}
                              <li class="is-active"><a>账号信息</a></li>
                              {% endblock %}

                            </ul>
                        </div>



                    {% block content %}
                    <div class="columns is-mobile" style="border-bottom: #ededed solid 1px; padding-bottom: 1rem">
                        <div class="column is-narrow">
                            <figure class="image is-96x96">

                                {% if user.userprofile.image %}
                                    <img class="is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}">
                                    {% else %}
                                    <img class="is-rounded" src=" {% static 'users/images/default.jpg' %}">
                                {% endif %}


                            </figure>
                        </div>
                        <div class="column is-narrow">
                            <div style="padding-top: 1.5rem;">

                                {% if user.userprofile.nike_name %}
                                    <h1 class="title is-size-4">{{ user.userprofile.nike_name }}</h1>
                                    {% else %}
                                    <h1 class="title is-size-4">{{ user.username }}</h1>
                                {% endif %}


                                {% if user.userprofile.gexing %}
                                    <p class="subtitle is-size-6">{{ user.userprofile.signature }}</p>
                                    {% else %}
                                    <p class="subtitle is-size-6">暂未设置个性签名</p>
                                {% endif %}


                            </div>
                        </div>
                        <div class="column is-narrow-mobile">
                            <a class=" button is-light is-pulled-right" href="{% url 'users:editor_users' %}" style="margin-top: 1.8rem">修改信息</a>
                        </div>
                    </div>

                    <div class="columns" style="padding:1rem 0; ">
                        <div class="column is-2">
                            <p>个人信息</p>
                        </div>
                        <div class="column">
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">昵称</span>
                                </div>
                                    <div class="column is-narrow">
                                        {% if user.userprofile.nike_name %}
                                        <span class=" has-text-black-ter">{{ user.userprofile.nike_name }}</span>
                                        {% else %}
                                        <span class=" has-text-black-ter">暂未设置用户昵称</span>
                                        {% endif %}

                                    </div>
                                <!-- <div class="column has-text-right">
                                    <a href="">更改类型</a>
                                </div> -->

                            </div>
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">性别</span>
                                </div>
                                <div class="column is-narrow">
                                    {% if user.userprofile %}
                                    <span class=" has-text-black-ter">{{ user.userprofile.get_gender_display }}</span>
                                    {% else %}
                                    <span class=" has-text-black-ter">暂未设置</span>
                                    {% endif %}
                                </div>

                            </div>
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">邮箱</span>
                                </div>
                                <div class="column is-narrow">
                                    <span class=" has-text-black-ter">{{ user.email }}</span>
                                </div>

                            </div>

                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">地址</span>
                                </div>
                                <div class="column is-narrow">
                                    {% if user.userprofile %}
                                    <span class=" has-text-black-ter">{{ user.userprofile.address }}</span>
                                    {% else %}
                                    <span class=" has-text-black-ter">暂未添加地址</span>
                                    {% endif %}

                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="columns" style="padding:1rem 0; ">
                        <div class="column is-2">
                            <p>个人简介</p>
                        </div>
                        <div class="column">
                            <div class="content">
                                {% if user.userprofile.desc %}
                                {{ user.userprofile.desc }}
                                {% else %}
                                暂未设置
                                {% endif %}

                            </div>
                        </div>
                    </div>
                    {% endblock  %}

                    </div>
                </div>
            </div>

        </div>
    </section>



</body>
</html>