mysite/blog/urls.py
# -*-coding:utf-8-*-
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from utils.upload import upload_file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls')),

    path('uploads/', upload_file, name='upload')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
# -*-coding:utf-8-*-
from django.urls import path
from . import views

app_name = 'users'  # 定义一个命名空间，用来区分不同应用之间的链接地址

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('active/<active_code>', views.active_user, name='active_user'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forget_pwd_url/<active_code>', views.forget_pwd_url, name='forget_pwd_url'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('logout/', views.logout_view, name='logout'),
    path('editor_users/', views.editor_users, name='editor_users'),
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.functional import cached_property  # 缓存装饰器
from django.template.loader import render_to_string  # 渲染模板


# Create your models here.


class Category(models.Model):
    """ 博客的分类模型 """
    name = models.CharField(max_length=32, verbose_name="分类名称")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="分类描述")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """ 文章标签 """
    name = models.CharField(max_length=10, verbose_name="文章标签")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    """ 文章 """
    title = models.CharField(max_length=61, verbose_name="文章标题")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="文章描述")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    content = models.TextField(verbose_name="文章详情")
    tags = models.ForeignKey(Tag, blank=True, null=True, on_delete=models.CASCADE, verbose_name="文章标签")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
    is_hot = models.BooleanField(default=False, verbose_name="是否热门")  # 手动热门推荐

    pv = models.IntegerField(default=0, verbose_name="浏览量")  # 浏览量
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Sidebar(models.Model):
    # 侧边栏的模型数据

    STATUS = (
        (1, '隐藏'),
        (2, '展示')
    )

    DISPLAY_TYPE = (
        (1, '搜索'),
        (2, '最新文章'),
        (3, '最热文章'),
        (4, '最近评论'),
        (5, '文章归档'),
        (6, 'HTML')
    )

    title = models.CharField(max_length=50, verbose_name="模块名称")  # 模块名称
    display_type = models.PositiveIntegerField(default=1, choices=DISPLAY_TYPE,
                                               verbose_name="展示类型")  # 侧边栏  搜索框/最新文章/热门文章/HTML自定义等
    content = models.CharField(max_length=500, blank=True, default='', verbose_name="内容",
                               help_text="如果设置的不是HTML类型，可为空")  # 这个字段是专门用来给HTML类型用的，其他类型可为空
    sort = models.PositiveIntegerField(default=1, verbose_name="排序", help_text='序号越大越靠前')
    status = models.PositiveIntegerField(default=2, choices=STATUS, verbose_name="状态")  # 隐藏  显示状态
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")  # 时间

    class Meta:
        verbose_name = "侧边栏"
        verbose_name_plural = verbose_name
        ordering = ['-sort']

    def __str__(self):
        return self.title

    @classmethod  # 类方法装饰器，这个就变成了这个类的一个方法可以调用
    def get_sidebar(cls):
        return cls.objects.filter(status=2)  # 查询到所有允许展示的模块

    @property  # 成为一个类属性，调用的时候不需要后边的（）,是只读的，用户没办法修改
    def get_content(self):
        if self.display_type == 1:
            context = {

            }
            return render_to_string('blog/sidebar/search.html', context=context)
        elif self.display_type == 2:
            context = {

            }
            return render_to_string('blog/sidebar/new_post.html', context=context)
        elif self.display_type == 3:
            context = {

            }
            return render_to_string('blog/sidebar/hot_post.html', context=context)
        elif self.display_type == 4:
            context = {

            }
            return render_to_string('blog/sidebar/commment.html', context=context)
        elif self.display_type == 5:  # 文章归档
            context = {

            }
            return render_to_string('blog/sidebar/archives.html', context=context)
        elif self.display_type == 6:  # 自定义侧边栏

            return self.content  # 在侧边栏直接使用这里的html，模板中必须使用safe过滤器去渲染HTML

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, F
from django.core.paginator import Paginator
from .models import Category, Post


def index(request):
    # 首页
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blog/index.html', context)


def category_list(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    # 获取当前分类下的所有文章
    posts = category.post_set.all()
    paginator = Paginator(posts, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')  # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {'category': category, 'page_obj': page_obj}
    return render(request, 'blog/list.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    prev_post = Post.objects.filter(id__lt=post_id).last()  # 上一篇
    next_post = Post.objects.filter(id__gt=post_id).first()  # 下一篇
    Post.objects.filter(id=post_id).update(pv=F('pv')+1)

    context = {'post': post, 'prev_post': prev_post, 'next_post': next_post}
    return render(request, 'blog/detail.html', context)


def search(request):
    keyword = request.GET.get('keyword')

    if not keyword:
        post_list = Post.objects.all()
    else:
        post_list = Post.objects.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword) | Q(content__icontains=keyword))
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')  # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'blog/index.html', context)


def archives(request, year, month):
    # 文章归档列表页
    post_list = Post.objects.filter(add_date__year=year, add_date__month=month)
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, 'year': year, 'month': month}
    return render(request, 'blog/archives_list.html', context)

mysite/blog/templates/blog/archives_list.html
{% extends 'blog/base.html' %}

{% block title %} {{ year }}{{ month }}的归档{% endblock %}

{% block archives %}
    <!-- 显示当前分类模块 -->
    <div class="box">
        每月归档：{{ year }}年{{ month }}月
        <div class="tags has-addons is-pulled-right">
          <span class="tag">共</span>
          <span class="tag is-primary">{{ post_list.count }} 篇</span>
        </div>
    </div>
    <!-- 显示当前分类模块 end-->
{% endblock  %}

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static category %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}messiys的博客{% endblock %}</title>
	<!-- <link rel="stylesheet" href="{% static 'users/bulma.css' %}"> -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

</head>

<body>

	<nav class="navbar is-warning container" role="navigation" aria-label="main navigation">
			<div class="navbar-brand">
				<a class="navbar-item" href="https://www.arsenal.com/">
					<img src="{% static 'users/images/web_site.png' %}" width="112" height="28">
				</a>

				<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
					data-target="navbarBasicExample">
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
				</a>
			</div>

			<div id="navbarBasicExample" class="navbar-menu">
				<div class="navbar-start">

					{% block navbar-start %}
					<a class="navbar-item" href="/">
						首页
					</a>

					{% get_category_list as category_list %}

						{% for category in category_list %}
						<a class="navbar-item" href="{% url 'blog:category_list' category.id %}">
							{{ category.name }}
						</a>
						{% endfor %}
					{% endblock %}
				</div>

				<div class="navbar-end">

					{% block navbar-end %}
					<div class="navbar-item">
						{% if user.is_authenticated %}
						<div class="buttons">
							<a class="button is-light" href="{% url 'users:user_profile' %}" target="_blank">
								<strong> {{ request.user.username }}</strong>
							</a>
							<a href="{% url 'users:logout' %}" class="button is-light">退出</a>
						</div>
						{% else %}
						<div class="buttons">
							<a class="button is-primary" href="{% url 'users:register' %}" target="_blank">
								<strong>注册</strong>
							</a>
							<a class="button is-light" href="{% url 'users:login' %}" target="_blank">
								登录
							</a>
						</div>
						{% endif %}
					</div>
					{% endblock %}
				</div>
			</div>
	</nav>
	<section class="section">
		<div class=" container">
			<div class="columns">
				<div class="column is-8">
					{% block section %}
					{% block archives %}{% endblock  %}

					{% if page_obj %}
					{% for post in page_obj %}
					<div class="box">
						<h1 class="is-size-5 has-text-weight-bold">
							<a href="{% url 'blog:post_detail' post.id %}"> {{ post.title }}</a>
						</h1>
						<div class=" is-size-7 has-text-grey-light pt-1 pb-1">
							<span class="mr-3">作者：{{ post.owner }}</span> <span>发布日期：{{ post.add_date }}</span>
						</div>
						<!-- https://docs.djangoproject.com/zh-hans/3.2/ref/templates/builtins/#truncatechars  官方文档 -->
						<p class="mt-3">{{ post.desc|truncatechars:50 }}</p>
					</div>
					{% endfor %}
					{% else %}
					<div class="box">
						<p class="has-text-danger">文章不存在！</p>
					</div>
					{% endif %}
					<!--  文档： https://docs.djangoproject.com/zh-hans/3.2/ref/paginator/#django.core.paginator.Paginator -->
					{% if page_obj %}
						<nav class="pagination is-centered" role="navigation" aria-label="pagination">
						{% if page_obj.has_previous %}
							<a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
						{% endif %}
						{% if page_obj.has_next %}
						<a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
						{% endif %}
						<ul class="pagination-list">
						{% if page_obj.has_previous %}
							<li><a class="pagination-link" aria-label="Goto page 45" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
						{% endif %}
							<li><a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page" href='?page={{ page_obj.number }}'>{{ page_obj.number }}</a></li>
						{% if page_obj.has_next %}
							<li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}" aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
						{% endif %}
						</ul>
						</nav>
						{% endif %}
					{% endblock %}
				</div>
				<div class="column is-4">

					{% block right %}
					{% get_sidebar_list as sidebar_list %}

					{% for sidebar in sidebar_list %}
					<div class="box">
						<h1 class=" is-size-5 title">{{ sidebar.title }}</h1>
						<p>{{ sidebar.get_content|safe }}</p>
					</div>

					{% endfor %}

					{% endblock %}

				</div>
			</div>

		</div>
	</section>

	{% block footer %}
	<footer class="footer container">
		<div class=" has-text-centered">
			这是博客的底部
		</div>
	</footer>
	{% endblock %}

</body>

</html>

mysite/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block section %}
<div class="box">
    <h1 class="is-size-5 has-text-weight-bold">
        <a> {{ post.title }}</a>
    </h1>
    <div class=" is-size-7 has-text-grey-light pt-1 pb-1">
        <span class="mr-3">作者：{{ post.owner }}</span> <span>发布日期：{{ post.add_date }}</span> <span>浏览量：{{ post.pv }}</span>
    </div>
    <div class="content">
        {{ post.content|safe }}
    </div>
</div>

<div class="box">
    <div class="level">
        <div class="level-left">

            {% if prev_post %}
            <span>上一篇：</span><a href="{% url 'blog:post_detail' prev_post.id %}" class="level-item">{{ prev_post.title }}</a>
            {% else %}
            <span class=" has-text-danger-dark is-size-7">无上一篇</span>
            {% endif %}
        </div>
        <div class="level-right">
            {% if next_post %}
            <span>下一篇：</span><a href="{% url 'blog:post_detail' next_post.id %}" class="level-item">{{ next_post.title }}</a>
            {% else %}
            <span class=" has-text-danger-dark is-size-7">已经是最后一篇</span>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

mysite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block section %}
{% endblock %}

mysite/blog/templates/blog/list.html
{% extends 'blog/base.html' %}